### PR TITLE
Fixing TimeoutManager index validator for quoted schemas

### LINKED ISSUE #349: TimeoutEntity_EndpointIdx validation error due to braces "[" and "]" used in schema name, even though correct index defined.
Hi, had a chat with Andreas today about "TimeoutEntity_EndpointIdx" index column validation error on the TimeoutEntity table. Because my schema contains braces when provided to the NHibernate config because otherwise it would not be recognized as a good identifier due to the use of a hyphen, the query to determine the columns used in the index does not return any results.

nHibernateConfig.SetProperty(NHibernate.Cfg.Environment.DefaultSchema, "[IOCDS-Async_NServiceBus_Scheduling]");

**As a result the following log entries are created:**

2018-11-07 14:58:38,212 [10] DEBUG NServiceBus.TimeoutPersisters.NHibernate.Installer.IncorrectIndexDetector - Detected TimeoutEntity_EndpointIdx (, )

2018-11-07 14:58:38,213 [10] WARN  NServiceBus.TimeoutPersisters.NHibernate.Installer.IncorrectIndexDetector - The TimeoutEntity_EndpointIdx index has incorrect column order. This may cause significant performance degradation of message deferral. Consult NServiceBus NHibernate persistence documentation for details on how to create this index.

**Possibly this issue can be fixed here within the GetIndex method:**
https://github.com/Particular/NServiceBus.NHibernate/blob/21b64e933de12f05486384ab27558bca083564f6/src/NServiceBus.NHibernate/TimeoutPersisters/IncorrectIndexDetector.cs

**By changing the GetIndex code as follows (only showing a snippet of the entire body):**

```
if (typeof(MsSql2005Dialect).IsAssignableFrom(dialect.GetType())) 
{ 
    var restrictions = new string[5] 
    { 
        entity.Table.Catalog, 
        entity.Table.Schema
                            .TrimStart('[')
                            .TrimEnd(']'), 
        entity.Table.Name, 
        indexName, 
        null 
    }; 
    return new SqlServerIndex(connection.GetSchema("IndexColumns", restrictions)); 
} 
```

This fix targets the use of braces with the schema specifically, perhaps the other properties should also be checked in a similar way?

Regards,
Roel

### PR DESCRIPTION
**Pull request by tmasternak**
Fixes #349

### CODE REVIEW

File: src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutsIndexValidator.cs [hunk 1]
```diff
@@ -75,19 +89,33 @@ public void LogWarningIfTimeoutEntityIndexIsIncorrect()
...
             if (typeof(MsSql2005Dialect).IsAssignableFrom(dialect.GetType()))
             {
-                var restrictions = new string[5]
+                string EnsureUnquoted(string name)
                 {
-                    entity.Table.Catalog,
-                    entity.Table.Schema,
-                    entity.Table.Name,
-                    indexName,
+                    if (null == name || name.Length < 2)
```
Comment (DavidBoike) [inline src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutsIndexValidator.cs]: I'm concerned there could be a hidden bug in all this math and substringing. Did you consider `Regex.Replace(name, @"[\[\]]+", "")`? (Just removes any `[` or `]` anywhere within the string.) Or does it have to be only on the boundaries to be removed?

Comment (tmasternak) [reply src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutsIndexValidator.cs]: So what this does is the following:
  * It **does not** validate if the identifier is correct
  * If the identifier is wrapped in `[]` it assumes that it's quoted and:
   * Removes the wrapping `[]` brackets
   * Replaces all double right brackets `]]` with a single one `]`. This is needed because right brackets need to be escaped in quoted identifiers.

This is a less generic version of (unquote) [https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.SqlServer/Addressing/NameHelper.cs#L17] logic in SqlServer transport.

Comment (DavidBoike) [reply src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutsIndexValidator.cs]: :+1: I meant it as a curiosity more than anything, no need to change.

File: src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_checking_db_indexes.cs [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+    using global::NHibernate.Tool.hbm2ddl;
+    using NUnit.Framework;
+    using TimeoutPersisters.NHibernate.Config;
+    using TimeoutPersisters.NHibernate.Installer;
+
+    class When_checking_db_indexes
+    {
+        SchemaExport schemaExport;
+
+        string dbSchemaName;
```
[the remark this answers is not in the document]
Comment (tmasternak) [reply src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_checking_db_indexes.cs]: In this case, the reason why those are global variables is that we need them in `TearDown` method to clean-up. Otherwise, the clean-up would have to be duplicated in each method.
